apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: elk-stack
  labels:
    app: kibana
    component: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    name: http
  selector:
    app: kibana